In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

marks = np.array([90, 80, 70, 60, 50, 40, 30, 20, 10, 0])
print(marks)

[90 80 70 60 50 40 30 20 10  0]


In [5]:
print("Mean: ", np.mean(marks))
print("Median: ", np.median(marks))
print("Max: ", np.max(marks))
print("Min: ", np.min(marks))
print("Sum: ", np.sum(marks))

Mean:  45.0
Median:  45.0
Max:  90
Min:  0
Sum:  450


In [6]:
print(marks + 5)

[95 85 75 65 55 45 35 25 15  5]


In [7]:
print(marks * 2)

[180 160 140 120 100  80  60  40  20   0]


In [8]:
marks_list = [12, 45, 23, 67, 74, 99]
print(sum(marks_list) / len(marks_list))

53.333333333333336
