In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

marks = np.array([90, 80, 70, 60, 50, 40, 30, 20, 10, 0])
print(marks)

[90 80 70 60 50 40 30 20 10  0]


In [5]:
print("Mean: ", np.mean(marks))
print("Median: ", np.median(marks))
print("Max: ", np.max(marks))
print("Min: ", np.min(marks))
print("Sum: ", np.sum(marks))

Mean:  45.0
Median:  45.0
Max:  90
Min:  0
Sum:  450


In [6]:
print(marks + 5)

[95 85 75 65 55 45 35 25 15  5]


In [7]:
print(marks * 2)

[180 160 140 120 100  80  60  40  20   0]


In [8]:
marks_list = [12, 45, 23, 67, 74, 99]
print(sum(marks_list) / len(marks_list))

53.333333333333336


In [9]:
import numpy as np

In [11]:
data = np.array([
    [78, 85, 90],
    [24, 56, 71],
    [12, 89, 34]
])
print(data)

[[78 85 90]
 [24 56 71]
 [12 89 34]]


In [12]:
print(data.shape)

(3, 3)


In [13]:
print(data[0])

[78 85 90]


In [22]:
print(data[1,0])

24


In [25]:
print(data[:,0])

[78 24 12]


In [31]:
print(np.mean(data, axis = 0))

[38.         76.66666667 65.        ]


In [32]:
print(np.mean(data, axis = 1))

[84.33333333 50.33333333 45.        ]


In [36]:
print(np.max(data))
print(np.min(data))
print(np.sum(data))

90
12
539


In [37]:
print(data + 5)

[[83 90 95]
 [29 61 76]
 [17 94 39]]
